name: Deploy master
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        dotnet-version: 6.0.x
    - name: Run ls command
      run: |
        cd D:\a\backended\backended\DotNET_Projects
        ls
